INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Bug',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Bug',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Bug',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Bug',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Bug',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Bug',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Bug',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Bug',
1);