INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Poison',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Poison',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Poison',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Poison',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Poison',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Poison',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Poison',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Poison',
0.5);