INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Rock',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Rock',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Rock',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Rock',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Rock',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Rock',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Rock',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Rock',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Rock',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Rock',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Rock',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Rock',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Rock',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Rock',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Rock',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Rock',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Rock',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Rock',
1);