INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Grass',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Grass',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Grass',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Grass',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Grass',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Grass',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Grass',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Grass',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Grass',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Grass',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Grass',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Grass',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Grass',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Grass',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Grass',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Grass',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Grass',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Grass',
1);