INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Dark',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Dark',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Dark',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Dark',
0);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Dark',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Dark',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Dark',
2);