INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Water',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Water',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Water',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Water',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Water',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Water',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Water',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Water',
1);