INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Ground',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Ground',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Ground',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Ground',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Ground',
0);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Ground',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Ground',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Ground',
1);