INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Fire',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Fire',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Fire',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Fire',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Fire',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Fire',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Fire',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Fire',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Fire',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Fire',
0.5);