INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Ice',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Ice',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Ice',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Ice',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Ice',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Ice',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Ice',
1);