INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Fairy',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Fairy',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Fairy',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Fairy',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Fairy',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Fairy',
0);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Fairy',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Fairy',
1);