INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Flying',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Flying',
0);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Flying',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Flying',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Flying',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Flying',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Flying',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Flying',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Flying',
1);