INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Ghost',
0);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Ghost',
0);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Ghost',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Ghost',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Ghost',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Ghost',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Ghost',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Ghost',
1);