INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Steel',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Steel',
0);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Steel',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Steel',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Steel',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Steel',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Steel',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Steel',
0.5);