INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Normal',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fighting',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Flying',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Poison',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ground',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Rock',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Bug',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ghost',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Steel',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fire',
'Dragon',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Water',
'Dragon',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Grass',
'Dragon',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Electric',
'Dragon',
0.5);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Psychic',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Ice',
'Dragon',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dragon',
'Dragon',
2);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Dark',
'Dragon',
1);
INSERT INTO PMOLENDA.TYPES_EFFECTIVENESS values ( 'Fairy',
'Dragon',
2);